# /!\ do NOT mix stable + edge! /!\
FROM alpine:edge

WORKDIR /root

VOLUME ["/root/project"]

# testing is not enabled by default
RUN echo 'https://dl-cdn.alpinelinux.org/alpine/edge/testing/' >> /etc/apk/repositories

# install
RUN apk add --no-cache npm

# default for react (node)
EXPOSE 3000

# vim: set expandtab ft=dockerfile:
